language: cpp
matrix:
    include:
        - os: osx
          before_install:
              - brew update
              - brew install qt5
              - brew link --force qt5
        - os: linux
          sudo: required
          before_install:
              - sudo apt-get -qq update
              - sudo apt-get -qq install qt5-default
install:
    - qmake
    - make
script:
    - echo "Finished"
